import { TaxModuleKey, TaxModuleMeta } from '../models/dashboard.model';

export const TAX_MODULES_CONFIG: Record<TaxModuleKey, TaxModuleMeta> = {
  automotores: {
    key: 'automotores',
    code: 'IMP-AUT-01',
    name: 'Impuesto sobre Vehículos Automotores',
    shortName: 'Vehículos',
    subtitle: 'Control de recaudo, censo vehicular, expedientes y liquidaciones de automotores',
    icon: 'fa-solid fa-car-side',
    badge: 'Módulo Vehicular',
    primaryColor: '#1e3a7b',
    accentColor: '#70b238',
    lightBg: 'bg-blue-50/50',
    darkBg: 'bg-[#0f172a]',
    entityName: 'Vehículos',
    apiEndpoint: '/vehiculos',
  },
  registros: {
    key: 'registros',
    code: 'IMP-REG-02',
    name: 'Impuesto de Registro Departamental',
    shortName: 'Registros',
    subtitle: 'Liquidación y registro de escrituras públicas, contratos notariales y actos comerciales',
    icon: 'fa-solid fa-file-contract',
    badge: 'Módulo de Registro',
    primaryColor: '#0f766e',
    accentColor: '#d97706',
    lightBg: 'bg-teal-50/50',
    darkBg: 'bg-[#042f2e]',
    entityName: 'Actos Registrales',
    apiEndpoint: '/registro',
  },
  licores: {
    key: 'licores',
    code: 'IMP-LIC-03',
    name: 'Impuesto al Consumo de Licores y Vinos',
    shortName: 'Licores',
    subtitle: 'Monitoreo de señalización, tornaguías, estampillas y consumo de licores departamentales',
    icon: 'fa-solid fa-wine-bottle',
    badge: 'Módulo Licores',
    primaryColor: '#831843',
    accentColor: '#10b981',
    lightBg: 'bg-pink-50/50',
    darkBg: 'bg-[#500724]',
    entityName: 'Tornaguías & Lotes',
    apiEndpoint: '/licores',
  },
  deguello: {
    key: 'deguello',
    code: 'IMP-DEG-04',
    name: 'Impuesto de Degüello de Ganado Menor y Mayor',
    shortName: 'Degüello',
    subtitle: 'Declaración, guías de movilización y control de sacrificio en plantas frigoríficas',
    icon: 'fa-solid fa-cow',
    badge: 'Módulo Degüello',
    primaryColor: '#78350f',
    accentColor: '#0284c7',
    lightBg: 'bg-amber-50/50',
    darkBg: 'bg-[#451a03]',
    entityName: 'Cabezas Sacrificadas',
    apiEndpoint: '/deguello',
  },
  sobretasa: {
    key: 'sobretasa',
    code: 'IMP-GAS-05',
    name: 'Sobretasa a la Gasolina y ACPM',
    shortName: 'Sobretasa Gasolina',
    subtitle: 'Declaraciones periódicas de distribuidores mayoristas y minoristas de combustible',
    icon: 'fa-solid fa-gas-pump',
    badge: 'Módulo Combustibles',
    primaryColor: '#ea580c',
    accentColor: '#2563eb',
    lightBg: 'bg-orange-50/50',
    darkBg: 'bg-[#431407]',
    entityName: 'Galones Declarados',
    apiEndpoint: '/sobretasa',
  },
  estampillas: {
    key: 'estampillas',
    code: 'IMP-EST-06',
    name: 'Estampillas Pro-Desarrollo y Bienestar',
    shortName: 'Estampillas',
    subtitle: 'Gravámenes a contratos y certificaciones públicas Pro-Cultura, Pro-Universidad y Adulto Mayor',
    icon: 'fa-solid fa-stamp',
    badge: 'Módulo Estampillas',
    primaryColor: '#4338ca',
    accentColor: '#059669',
    lightBg: 'bg-indigo-50/50',
    darkBg: 'bg-[#1e1b4b]',
    entityName: 'Retenciones',
    apiEndpoint: '/estampillas',
  },
  pasaporte: {
    key: 'pasaporte',
    code: 'TRAM-PAS-07',
    name: 'Gestión y Expedición de Pasaportes',
    shortName: 'Pasaportes',
    subtitle: 'Control de citas previas, estampillado departamental y formalización de pasaportes',
    icon: 'fa-solid fa-passport',
    badge: 'Módulo Pasaportes',
    primaryColor: '#0369a1',
    accentColor: '#ca8a04',
    lightBg: 'bg-sky-50/50',
    darkBg: 'bg-[#082f49]',
    entityName: 'Solicitudes',
    apiEndpoint: '/pasaportes',
  },
};
